### ISSUE TITLE
Does ipex support the Qwen3 model?

### ISSUE THREAD

**Issue by wuwei32454** [intel/intel-extension-for-pytorch#827]
### Describe the issue

Hi ,
When I run Qwen3 model with ipex  (version 2.6),  errors occur with the following messages:
~~~
Traceback (most recent call last):
  File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1034, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 736, in __getitem__
    raise KeyError(key)
KeyError: 'qwen3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/llm/inference/single_instance/run_generation.py", line 156, in <module>
    config = AutoConfig.from_pretrained(
  File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1036, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `qwen3` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
LLM RUNTIME ERROR: Running generation task failed. Quit.
~~~
Does ipex support the Qwen3 model?

**Comment by xiguiw** [comment]
@wuwei32454 

Please upgrade your transformers version.
For Qwen3 model, it requires transformers>=4.51.0

**Comment by wuwei32454** [comment]
Thanks for your reply.
I have updated the transformers version to 4.51.3.
```
Name: transformers
Version: 4.51.3
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /root/miniforge3/envs/py310/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: lm_eval, peft, transformers-stream-generator
```
Then there are no errors with 'qwen3', but other errors have occurred. Please check the following messages:
```
25-05-15 01:31:43,261 - launcher_base.py - IPEX-launcher - INFO - cmd: numactl -C 0-127 -m 0,1,2,3 python run.py --benchmark -m /mnt/Qwen3-32B --input-tokens 128 --max-new-tokens 128 --dtype bfloat16 --num-iter 1 --num-warmup 1 --batch-size 1 --ipex --token-latency
2025-05-15 01:31:43,261 - _logger.py - IPEX-launcher - WARNING - Cross NUMA nodes execution detected: cores [0-127] are on different NUMA nodes [0,1,2,3]
LLM RUNTIME INFO: running model geneartion...
['python', PosixPath('/root/llm/inference/single_instance/run_generation.py'), '-m', '/mnt/Qwen3-32B', '--dtype', 'bfloat16', '--input-tokens', '128', '--max-new-tokens', '128', '--num-iter', '1', '--num-warmup', '1', '--batch-size', '1', '--kv-cache-dtype', 'auto', '--ipex', '--deployment-mode', '--benchmark', '--token-latency']
Error.  nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (64)[2025-05-15 01:31:47,156] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
/root/miniforge3/envs/py310/lib/python3.10/site-packages/oneccl_bindings_for_pytorch/__init__.py:25: UserWarning: Warning: Cannot load xpu CCL. CCL doesn't work for XPU device due to /root/miniforge3/envs/py310/lib/python3.10/site-packages/oneccl_bindings_for_pytorch/lib/liboneccl_bindings_for_pytorch_xpu.so: cannot open shared object file: No such file or directory
  warnings.warn(f"Warning: Cannot load xpu CCL. CCL doesn't work for XPU device due to {e}")
[2025-05-15 01:31:47,158] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
Namespace(model_id='/mnt/Qwen3-32B', dtype='bfloat16', input_tokens='128', max_new_tokens=128, prompt=None, streaming=False, image_url='https://images.cocodataset.org/val2017/000000039769.jpg', audio='example.flac', config_file=None, greedy=False, ipex=True, deployment_mode=True, torch_compile=False, backend='ipex', profile=False, benchmark=True, num_iter=1, num_warmup=1, batch_size=1, token_latency=True, cache_weight_for_large_batch=False, vision_text_model=False, kv_cache_dtype='auto')
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 276.35it/s]
---- Prompt size: 128
/root/llm/inference/single_instance/run_generation.py:383: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.inference_mode(), torch.no_grad(), torch.cpu.amp.autocast(
/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Traceback (most recent call last):
  File "/root/llm/inference/single_instance/run_generation.py", line 436, in <module>
    output = model.generate(input_ids, **generate_kwargs)
  File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 2484, in generate
    result = self._beam_search(
  File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 3916, in _beam_search
    logits = model_outputs.logits[:, -1, :].to(copy=True, dtype=torch.float32, device=input_ids.device)
AttributeError: 'tuple' object has no attribute 'logits'
LLM RUNTIME ERROR: Running generation task failed. Quit.
```

![Image](https://github.com/user-attachments/assets/b43e1461-8a41-4c44-bcad-4fe2939622a1)

Do you have any solutions for the above errors?

**Comment by xiguiw** [comment]
> Thanks for your reply. I have updated the transformers version to 4.51.3.
> 
> ```
> Name: transformers
> Version: 4.51.3
> Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
> Home-page: https://github.com/huggingface/transformers
> Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
> Author-email: transformers@huggingface.co
> License: Apache 2.0 License
> Location: /root/miniforge3/envs/py310/lib/python3.10/site-packages
> Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
> Required-by: lm_eval, peft, transformers-stream-generator
> ```
> 
> Then there are no errors with 'qwen3', but other errors have occurred. Please check the following messages:
> 
> ```
> 25-05-15 01:31:43,261 - launcher_base.py - IPEX-launcher - INFO - cmd: numactl -C 0-127 -m 0,1,2,3 python run.py --benchmark -m /mnt/Qwen3-32B --input-tokens 128 --max-new-tokens 128 --dtype bfloat16 --num-iter 1 --num-warmup 1 --batch-size 1 --ipex --token-latency
> 2025-05-15 01:31:43,261 - _logger.py - IPEX-launcher - WARNING - Cross NUMA nodes execution detected: cores [0-127] are on different NUMA nodes [0,1,2,3]
> LLM RUNTIME INFO: running model geneartion...
> ['python', PosixPath('/root/llm/inference/single_instance/run_generation.py'), '-m', '/mnt/Qwen3-32B', '--dtype', 'bfloat16', '--input-tokens', '128', '--max-new-tokens', '128', '--num-iter', '1', '--num-warmup', '1', '--batch-size', '1', '--kv-cache-dtype', 'auto', '--ipex', '--deployment-mode', '--benchmark', '--token-latency']
> Error.  nthreads cannot be larger than environment variable "NUMEXPR_MAX_THREADS" (64)[2025-05-15 01:31:47,156] [WARNING] [real_accelerator.py:181:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
> /root/miniforge3/envs/py310/lib/python3.10/site-packages/oneccl_bindings_for_pytorch/__init__.py:25: UserWarning: Warning: Cannot load xpu CCL. CCL doesn't work for XPU device due to /root/miniforge3/envs/py310/lib/python3.10/site-packages/oneccl_bindings_for_pytorch/lib/liboneccl_bindings_for_pytorch_xpu.so: cannot open shared object file: No such file or directory
>   warnings.warn(f"Warning: Cannot load xpu CCL. CCL doesn't work for XPU device due to {e}")
> [2025-05-15 01:31:47,158] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cpu (auto detect)
> Namespace(model_id='/mnt/Qwen3-32B', dtype='bfloat16', input_tokens='128', max_new_tokens=128, prompt=None, streaming=False, image_url='https://images.cocodataset.org/val2017/000000039769.jpg', audio='example.flac', config_file=None, greedy=False, ipex=True, deployment_mode=True, torch_compile=False, backend='ipex', profile=False, benchmark=True, num_iter=1, num_warmup=1, batch_size=1, token_latency=True, cache_weight_for_large_batch=False, vision_text_model=False, kv_cache_dtype='auto')
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 276.35it/s]
> ---- Prompt size: 128
> /root/llm/inference/single_instance/run_generation.py:383: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
>   with torch.inference_mode(), torch.no_grad(), torch.cpu.amp.autocast(
> /root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
>   warnings.warn(
> /root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.95` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
>   warnings.warn(
> /root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
>   warnings.warn(
> The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
> Traceback (most recent call last):
>   File "/root/llm/inference/single_instance/run_generation.py", line 436, in <module>
>     output = model.generate(input_ids, **generate_kwargs)
>   File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 2484, in generate
>     result = self._beam_search(
>   File "/root/miniforge3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 3916, in _beam_search
>     logits = model_outputs.logits[:, -1, :].to(copy=True, dtype=torch.float32, device=input_ids.device)
> AttributeError: 'tuple' object has no attribute 'logits'
> LLM RUNTIME ERROR: Running generation task failed. Quit.
> ```
> 
> ![Image](https://github.com/user-attachments/assets/b43e1461-8a41-4c44-bcad-4fe2939622a1)
> 
> Do you have any solutions for the above errors?

Please update IPEX to 2.7.10
It works with 2.7.10-xpu at my side.
